config/routes.rb
Opp::Application.routes.draw do
   
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "messages_controller/new"
  get "messages_controller/create"

  resources :activity_sequences
  resources :activity_in_sequences

  mount Ckeditor::Engine => '/ckeditor'

  get "hals/view(/:tab)", to: 'hals#view', as: 'view_hals'
  get "hals/view/1", to: 'hals#view', as: 'hals_my_insights'
  get "hals/view/2", to: 'hals#view', as: 'hals_following'
  get "hals/view/3", to: 'hals#view', as: 'hals_my_courses'
  get "hals/view/4", to: 'hals#view', as: 'hals_all_hals'
  get "hals/view/5", to: 'hals#view', as: 'hals_help_wanted'
  get "hals/view/0", to: 'hals#view', as: 'hals_mine'
  
  get "courses/:id/4", to: 'courses#show', as: 'course_people'
  get "hals/edit/:id", to: 'hals#edit', as: 'edit_hal'
  get "hals/new_hal(/:id)", to: 'hals#new_hal', as: 'new_hal'

  resources :hals
  
  
  resources :activities, :collection => { :sort => :post }
  get "activity_sequences/sort", to: "activity_sequences#sort", as: 'sort_activity_sequences'
  get "activities/copy_activity/:id", to: "activities#copy_activity", as: 'copy_activity'

  get "activities/sort", to: "activities#sort", as: 'sort_activities'
  get "activities/show/:id", to: "activities#show", as: 'show_activity'
  get "activities/new", to: "activities#new",  as: 'add_activity'
  get "activity_in_sequences/add_to_sequence/:id", to: "activity_in_sequences#add_to_sequence",  as: 'add_activity_to_sequence'
  
  get "activities/add_activity_to_course/:id", to: "activities#add_activity_to_course",  as: 'add_activity_to_course'
  get "activities/edit_activity_in_course/:id", to: "activities#edit_activity_in_course",  as: 'edit_activity_in_course'
  
  post "activities/create_activity_in_course/:id", to: "activities#create_activity_in_course",  as: 'create_activity_in_course'
  get "strategies/copy_activity/:id", to: "strategies#copy_activity",  as: 'copy_activity'

  get "activities/mine", to: "strategies#mine",  as: 'user_strategy'
  get "strategies/mine?tut=true", to: 'strategies#mine', as: 'tut'  
  get "strategies/mine(/:id)", to: 'strategies#mine', as: 'myp'
  get "strategies/mine_details/:id", to: 'strategies#mine_details', as: 'mypd'

  get "commitment_marks", to: 'commitment_marks#mycms', as: 'mycms'

  get "courses/new", to: 'courses#new', as: 'create_course'
  get "courses/my_created", to: 'courses#my_created', as: 'my_created_courses'
  get "courses/new", to: 'courses#new', as: 'create_course'
  get "courses/my_created", to: 'courses#my_created', as: 'my_created_courses'
  get "courses/update_description/:id", to: 'courses#update_description', as: 'update_description'
  get "courses/publish_course/:id", to: 'courses#publish_course', as: 'publish_course'
  get "courses/edit_course/:id(/:tab)/(:actvitiy_id)", to: 'courses#edit_course', as: "edit_course"
  get "courses/edit_course/:id/0", to: 'courses#overview_edit', as: 'course_overview_edit'
  get "courses/edit_course/:id/1/(:actvitiy_id)", to: 'courses#edit_course', as: 'course_plan_edit'
  get "courses/edit_course/:id/2", to: 'courses#description_edit', as: 'course_description_edit'
  get "courses/:id(/:tab)", to: 'courses#show', as: 'show_course'
  get "courses/:id/4", to: 'courses#show', as: 'course_people'
  get "courses/:id/3", to: 'courses#show', as: 'course_blogs'
  get "courses/:id/2", to: 'courses#show', as: 'course_description'
  get "courses/:id/1", to: 'courses#show', as: 'course_plan'
  get "courses/:id/0", to: 'courses#show', as: 'course_overview'
  resources :courses
  

  match "share_course_on_fb/:id", to: "courses#share_course_on_fb", as: "share_course_on_fb"

  get "banner", to: 'info#banner', as: 'bann'
  get "about_us", to: 'info#about', as: 'about'
  get "eula", to: 'info#eula', as: 'eula'
  get "privacy", to: 'info#privacy', as: 'privacy'
  get "howitworks", to: 'info#howitworks', as: 'howitworks'
  get "gettingstartedcreate", to: 'info#gettingstartedcreate', as: 'gettingstartedcreate'
  get "gettingstartedoverview", to: 'info#gettingstartedoverview', as: 'gettingstartedoverview'

  get "contact_us", to: 'messages#new', as: 'contact_us'
  match "newsletter", to: 'messages#news', as: 'newsletter'
  resources :messages

  match "add_commitment_mark_to_activity/:activity_id", :controller => "commitment_marks", :action => "add_commitment_mark_to_activity"

  match 'my_plan/:id',  :controller => "strategies", :action => "mine", :activity_id => :id

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  ActiveAdmin.routes(self)
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new", as: 'signin'
    get "sign_out", :to => "devise/sessions#destroy" #destroy_user_session"
  end  # devise_for :users
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => 'registrations'}
  ActiveAdmin.routes(self)
  ActiveAdmin.routes(self)

  match 'auth/:provider/callback', to: 'sessions#create'
  
  match 'auth/facebook/callback?error', to: redirect('/')
  match 'auth/facebook/callback?error_code', to: redirect('/')
  
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
    
  get 'users/follow_user/:id',:to => 'users#follow_user', as: 'follow'
  match 'users/login_or_signup',  :controller => "users", :action => "login_or_signup"
  match 'users/myprofile',  :controller => "users", :action => "myprofile", :as => "my_profile"
  match 'users/editmyprofile',  :controller => "users", :action => "edit_profile", :as => "edit_profile"

  resources :users do
    member do
      put :follow
      put :unfollow
    end
  end
  
  
  resources :comments

  match 'join_course/:id',  :controller => "courses", :action => "join", :as => "join_course"

  match 'co',  :controller => "courses", :action => "index"
  root :to => "home#index"
 
  

  match ':controller(/:action(/:id))(.:format)'
  
  
  
end

app/views/shared/_aside.html.erb
<% if current_user %>
 <div class="right">
	<aside>
	<div class="box_holder">
			<div class="title"><h3>Updates</h3></div>
			<div class="triangle2"></div>
			<% @udpates.each do |update| %>
				<% if update.action and update.loggable %>
					<div class="box_holder2">
						<%= 
						# update.id
						 %> 
						<p>
							<%= link_to update.user.name, update.user %>&nbsp; <%= render "update/#{update.loggable_type.downcase}/#{update.action.downcase}", update: update %>
						</p>
					</div>
				<% end %>
			<% end %>
	</div>
	</aside>
 </div>
<% end %>

app/views/shared/_debug.html.erb
<div id="debug">
<% if current_user %>
	Current user id: <%= current_user.id %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=303696459779708";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="nav2">
	<ul>
		<li> <%= link_to "EULA", eula_path %></li>
		<li> <%= link_to "Privacy Statement", privacy_path %></li>
		<li> <%= link_to "Contact Us", :contact_us %></li>
	</ul>
</div>

	<div class="copy">Copyright ©2010 - 2014. All Rights Reserved</div>
	
	<div class="footerlink">
	        <div class="facebooklink_footer">
	          <div class="fb-like" data-href="https://www.facebook.com/melearningapp" data-layout="button" data-action="like" data-show-faces="false" data-share="false"></div>
	        </div>
	        <div class="twitterlink_footer"> <a href="https://twitter.com/melearningapp" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @melearningapp</a>
	          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
	        </div>
			</div>	

app/views/shared/_menu.html.erb
<% if user_signed_in? -%>
	<div id="menuBarBg"><span></span></div>
		<div class="width">
			<div id="page">
				<div id="menuBar">
					<div id="menuCorners"></div>
					<ul id="menu">
						<li><%= link_to 'Home', :root %></li>
						<li><%= link_to 'My Strategy', '/view_mine' %></li> 
						<li><%= link_to 'Browse Strategies', "/list" %></li>
						<li><%= link_to 'My HAL', "/view_my_hals" %></li>
						<li><%= link_to 'My Insights', "/view_my_insights" %></li>
						<li><%= link_to 'Everyone\'s HAL', '/view_all'%></li>
						<li><%= link_to 'Other users', '/view_all_users'%></li>
						<li><%= link_to 'Forum', :root %></li>
						<li><%= link_to 'My Profile', :root %></li>
						<li><%= link_to 'Resources', :root  %></li>
					</ul>
											</div>

<% else -%>
<div id="menuBarBg"><span></span></div>
	<div class="width">
		<div id="page">
			<div id="menuBar">
				<div id="menuCorners"></div>
				<ul id="menu">
					<li><%= link_to 'Home', :root %></li>
					<li><%= link_to 'Resources', :root  %></li>
					<li><%= link_to 'About', "about" %></li>
				</ul>
				</div>

<% end -%>

app/views/shared/_menu_bar.html.erb
	<%= content_tag :div, class: "logo" do -%>
 		<%= link_to image_tag("/images/lobehold.png", :style => "width:180px"), root_path %><BR>
	<% end -%>
	<nav>
		<ul>
		<% if current_user  %>
			<li id='linkplan'><div data-intro="This is where you have your plan.  You'll be spending a lot of time here.  You can manage your plan, and view your commitment marks" data-step='1'> <%= link_to "my Plan", :myp, class: 'stra'  %>  </div>
				<ul id="navmenuplan">
					<li><%= link_to "My Plan", :myp  %></li>
		            <li class="divider"></li>
		            <li><%= link_to "Commitment Marks", :mycms %></li>
				</ul>
				
			</li>
			 <li id='link1'> <div data-intro='All blogs are here: for your courses, general blogs, your own, the people you follow.  Blog early, blog often.' data-step='2'> <%= link_to "Blog", :view_hals, class: 'blog' %></div>
				<ul id="navmenu1">
					<li><%= link_to "add an entry", new_hal_path  %></li>
		            <li class="divider"></li>
		            <li><%= link_to "View Blogs", :view_hals %></li>
				</ul>
			</li>
		<% end %>

		<li id='link2'> <div data-intro='Courses can be found here.  You can create a course.  You can browse all listed ones, and see the ones you follow, the ones you create.' data-step='3'> 
		<a href="/courses" class="course">Courses</a></div>
			<ul id="navmenu2">
                <li><a href="/courses">Browse courses</a></li>
				<% if (current_user && current_user.get_following_courses.size>0) %>
				<li id="link2a"><a href="#" title="Courses Plan">Courses I follow</a>
					<ul id="navmenu2a">
						<% 	current_user.get_following_courses.each do |course| %>
							<li><%= link_to course.name, course %></li>
						<% end %>
					</ul>
				</li>
				<% end %>
				<% if (current_user && current_user.courses.size>0) %>
				<li id="link2b"><a href="#" title="Courses Explanation">Courses I created</a>
					<ul id="navmenu2b">
						<% 	current_user.courses.each do |course| %>
						<li><%= link_to course.name, edit_course_path(course) %></li>
						<% end %>
					</ul>
				</li>
									
				<% end %>
                <li class="divider"></li>
                <li><a href="/courses/new">create a course</a></li>
			</ul>
		</li>
	 </ul>
		
	</nav>
	<% if current_user  %>	
	<!-- <div style="float:left; margin-left:10px;"><a href="#"><img src="/images/getting_started.jpg" alt=""></a></div> -->
	<% end %>

	<% if current_user  %>
	<div class="user">
		<div class="image">
			<div class="image2">
				<%= image_tag current_user.avatar.url(:thumb) if (current_user and current_user.avatar.url(:thumb)) %>
			</div>
		</div>
		<div class="name"><a href="#"><%= current_user.name %></a> 
			<ul>
				<li><%= link_to "profile", "/users/myprofile" %></li>
			    <li><%= link_to "Sign out", sign_out_path %></li>
			</ul>
		</div>
	</div>


	<div class="getstart">
	    <div class="name"><a href="javascript:void(0);" data-intro='Welcome to the quick tour.  You can click the right arrow to go to the next step.' data-step='0'>Getting Started</a>
	      <ul>
				<% if current_page?(myp_path) %>
					<li><a href="javascript:void(0);" onclick="inanimateshowdiv('<%= current_user.strategy.current_activities.first.id if current_user.strategy.current_activities.first %>');$(window).scrollTop(0);introJs().start();">mini Tutorial</a></li>
				<% else %>
		            <li><%= link_to "mini Tutorial", tut_path %></li>
				<% end %>
	          <li><%= link_to "Getting started", :gettingstartedoverview %></li>
	          <li><%= link_to "How it works", howitworks_path %></li>
	          <li><%= link_to "Creating a course", gettingstartedcreate_path %></li>
	      </ul>
	    </div>
	</div>
	<div class="clear"></div>	
	<% else %>
	<div class="userlogin">
		<%= link_to image_tag("/images/fb_login.png"), "/auth/facebook", :class => "fblogin", :alt=>"Facebook Login", id: "sign_in" %>
		<input name="login" value="Login" type="button" class="loginbtn" onClick="location.href='<%= new_user_session_path %>'">
		<div class="clear"></div>
	</div>
	<% end %>
<!--  yuser<%= current_user.id if current_user %> -->

app/views/shared/_tag_display.html.erb
<% if !tags.blank? %>
	<strong>Tags: </strong><%= tags.map(&:name).join(", ") %>
<% end %>

app/views/shared/_updates.html.erb
<% @udpates.each do |update| %>
	<%= update.id %> <%= link_to update.user.name, update.user %> 
	<%= render "update/#{update.loggable_type.downcase}/#{update.action.downcase}", update: update %>
	<BR>
<% end %>

app/views/shared/_user_bar.html.erb
  <% if user_signed_in? %>
    	<span>Welcome</span>
	<%= current_user.name %>
	<%= link_to "profile", "/users/myprofile" %>
    <%= link_to "Sign out", sign_out_path %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>    -     
<%= link_to "	with FB:", "/auth/facebook", id: "sign_in" %>

  <% end %>



<%= 
# link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) 
%>