config/routes.rb
Opp::Application.routes.draw do
   
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "messages_controller/new"
  get "messages_controller/create"

  resources :activity_sequences
  resources :activity_in_sequences

  mount Ckeditor::Engine => '/ckeditor'

  get "hals/view(/:tab)", to: 'hals#view', as: 'view_hals'
  get "hals/view/1", to: 'hals#view', as: 'hals_my_insights'
  get "hals/view/2", to: 'hals#view', as: 'hals_following'
  get "hals/view/3", to: 'hals#view', as: 'hals_my_courses'
  get "hals/view/4", to: 'hals#view', as: 'hals_all_hals'
  get "hals/view/5", to: 'hals#view', as: 'hals_help_wanted'
  get "hals/view/0", to: 'hals#view', as: 'hals_mine'
  
  get "courses/:id/4", to: 'courses#show', as: 'course_people'
  get "hals/edit/:id", to: 'hals#edit', as: 'edit_hal'
  get "hals/new_hal(/:id)", to: 'hals#new_hal', as: 'new_hal'

  resources :hals
  
  
  resources :activities, :collection => { :sort => :post }
  get "activity_sequences/sort", to: "activity_sequences#sort", as: 'sort_activity_sequences'
  get "activities/copy_activity/:id", to: "activities#copy_activity", as: 'copy_activity'

  get "activities/sort", to: "activities#sort", as: 'sort_activities'
  get "activities/show/:id", to: "activities#show", as: 'show_activity'
  get "activities/new", to: "activities#new",  as: 'add_activity'
  get "activity_in_sequences/add_to_sequence/:id", to: "activity_in_sequences#add_to_sequence",  as: 'add_activity_to_sequence'
  
  get "activities/add_activity_to_course/:id", to: "activities#add_activity_to_course",  as: 'add_activity_to_course'
  get "activities/edit_activity_in_course/:id", to: "activities#edit_activity_in_course",  as: 'edit_activity_in_course'
  
  post "activities/create_activity_in_course/:id", to: "activities#create_activity_in_course",  as: 'create_activity_in_course'
  get "strategies/copy_activity/:id", to: "strategies#copy_activity",  as: 'copy_activity'

  get "activities/mine", to: "strategies#mine",  as: 'user_strategy'
  get "strategies/mine?tut=true", to: 'strategies#mine', as: 'tut'  
  get "strategies/mine(/:id)", to: 'strategies#mine', as: 'myp'
  get "strategies/mine_details/:id", to: 'strategies#mine_details', as: 'mypd'

  get "commitment_marks", to: 'commitment_marks#mycms', as: 'mycms'

  get "courses/new", to: 'courses#new', as: 'create_course'
  get "courses/my_created", to: 'courses#my_created', as: 'my_created_courses'
  get "courses/new", to: 'courses#new', as: 'create_course'
  get "courses/my_created", to: 'courses#my_created', as: 'my_created_courses'
  get "courses/update_description/:id", to: 'courses#update_description', as: 'update_description'
  get "courses/publish_course/:id", to: 'courses#publish_course', as: 'publish_course'
  get "courses/edit_course/:id(/:tab)/(:actvitiy_id)", to: 'courses#edit_course', as: "edit_course"
  get "courses/edit_course/:id/0", to: 'courses#overview_edit', as: 'course_overview_edit'
  get "courses/edit_course/:id/1/(:actvitiy_id)", to: 'courses#edit_course', as: 'course_plan_edit'
  get "courses/edit_course/:id/2", to: 'courses#description_edit', as: 'course_description_edit'
  get "courses/:id(/:tab)", to: 'courses#show', as: 'show_course'
  get "courses/:id/4", to: 'courses#show', as: 'course_people'
  get "courses/:id/3", to: 'courses#show', as: 'course_blogs'
  get "courses/:id/2", to: 'courses#show', as: 'course_description'
  get "courses/:id/1", to: 'courses#show', as: 'course_plan'
  get "courses/:id/0", to: 'courses#show', as: 'course_overview'
  resources :courses
  

  match "share_course_on_fb/:id", to: "courses#share_course_on_fb", as: "share_course_on_fb"

  get "banner", to: 'info#banner', as: 'bann'
  get "about_us", to: 'info#about', as: 'about'
  get "eula", to: 'info#eula', as: 'eula'
  get "privacy", to: 'info#privacy', as: 'privacy'
  get "howitworks", to: 'info#howitworks', as: 'howitworks'
  get "gettingstartedcreate", to: 'info#gettingstartedcreate', as: 'gettingstartedcreate'
  get "gettingstartedoverview", to: 'info#gettingstartedoverview', as: 'gettingstartedoverview'

  get "contact_us", to: 'messages#new', as: 'contact_us'
  match "newsletter", to: 'messages#news', as: 'newsletter'
  resources :messages

  match "add_commitment_mark_to_activity/:activity_id", :controller => "commitment_marks", :action => "add_commitment_mark_to_activity"

  match 'my_plan/:id',  :controller => "strategies", :action => "mine", :activity_id => :id

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  ActiveAdmin.routes(self)
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new", as: 'signin'
    get "sign_out", :to => "devise/sessions#destroy" #destroy_user_session"
  end  # devise_for :users
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => 'registrations'}
  ActiveAdmin.routes(self)
  ActiveAdmin.routes(self)

  match 'auth/:provider/callback', to: 'sessions#create'
  
  match 'auth/facebook/callback?error', to: redirect('/')
  match 'auth/facebook/callback?error_code', to: redirect('/')
  
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
    
  get 'users/follow_user/:id',:to => 'users#follow_user', as: 'follow'
  match 'users/login_or_signup',  :controller => "users", :action => "login_or_signup"
  match 'users/myprofile',  :controller => "users", :action => "myprofile", :as => "my_profile"
  match 'users/editmyprofile',  :controller => "users", :action => "edit_profile", :as => "edit_profile"

  resources :users do
    member do
      put :follow
      put :unfollow
    end
  end
  
  
  resources :comments

  match 'join_course/:id',  :controller => "courses", :action => "join", :as => "join_course"

  match 'co',  :controller => "courses", :action => "index"
  root :to => "home#index"
 
  

  match ':controller(/:action(/:id))(.:format)'
  
  
  
end

app/models/strategy.rb
class Strategy < ActiveRecord::Base
  acts_as_paranoid
  has_many :activities, :dependent => :destroy  #, :as => :activityable, :dependent => :destroy 
  has_many :goals, :dependent => :destroy
  has_many :activity_sequences, :dependent => :destroy 
  has_many :activity_in_sequences, through: :activity_sequences
  belongs_to :from, class_name: Strategy, :foreign_key => 'from_id'
  belongs_to :user

  has_many :hals, :as => :halable #, :dependent => :destroy
  has_many :from_template_hals, :as => :halable #, :dependent => :destroy
  
  
  #  get all activities in strategy combined with all current activities in activity sequences
  def current_activities
    ids = self.activities.pluck(:id) + ActivitySequence.where(strategy_id: self.id).pluck(:current_activity_id)
    if (ids.size > 0)
      ids.delete(nil)  # hack for now
     Activity.where( "id in (#{ids.join(',')})")
   else 
     Activity.where("1=0")  # hack to return empty AR relation.  
   end
  end
  
  # TODO
  # def get_all_activities
  # end/images
  
  def text
    "STRAT"
  end
  
  # checks if a goal with that title exists.  returns that or a new goal in the strategy
  def create_or_use_goal(goal_text)
    goal = Goal.where(title: goal_text, strategy_id: self.id, user_id: self.user.id, course_id: self.course_id).first
    goal ||= Goal.create!(title: goal_text, strategy_id: self.id, user_id: self.user.id, course_id: self.course_id)     
  end
    
  # if a strategy contains a specific activity as defined by same object or same origin of object (course or user)
  def contains_activity(activity)
    self.current_activities.each do |strat_activity|
      if (strat_activity.id == activity.id || strat_activity.from_id == activity.id || (strat_activity.from_id == activity.from_id && activity.from_id != nil))
        return true
      end
    end
    return false
  end
  
  def contains_activity_sequence(as)
    self.activity_sequences.each do |strat_as|
      if (strat_as.id == as.id || strat_as.from_id == as.id || (strat_as.from_id == as.from_id && as.from_id != nil))
        return true
      end
    end
    return false    
  end
  
  def contains_customizations
    self.current_activities.any? {|activity| !activity.customization.blank?}
  end
  
  # def copy_activity_to_strategy(activity)    
  #   strat_activity = activity.dup
  #   if (activity.from_id.nil?)
  #     strat_activity.from_id = activity.id
  #     strat_activity.save
  #   end
  #   self.activities << strat_activity
  # end
  
  def add_activity(activity)
    self.activities << activity
  end
    
  
  def self.c    
    s = Strategy.create()

    g = Goal.create(:title => "important")
    g2 = Goal.create(:title => "not very")
    
    a1 = Activity.create(:title => "title1111")
    g.activities << a1
    s.activities << a1
    a2 = Activity.create(:title => "title2222")
    g2.activities << a2
    s.activities << a2
    
    g3 = Goal.create(:title => "goal 3")
    a1 = Activity.create(:title => "title3333")
    a2 = Activity.create(:title => "imp activity")
    a3 = Activity.create(:title => "another act")
    g3.activities << a1
    s.activities << a2
    s.activities << a3
    stratact = Activity.create(:title => "stratact")
    s.activities << stratact
    s
  end

def print
  puts "user: #{self.user_id}"
  puts "activities: "
  self.current_activities.each {|activity| activity.print}
end
  
end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
  before_filter :authenticate_user!

  def mine
    @related_hals = Hal.get_hals_related_to_strategy(current_user.strategy)
    @udpates = ActionLog.latest(current_user)
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
    if params[:tut] == 'true'
      @tut = true
    else
      @tut = false
      @activity = Activity.find_by_id params[:id]
    end
  end

  def copy_activity
    @activity = Activity.find(params[:id])
    copy = @activity.copy_to_user(current_user)
    redirect_to myp_path(copy), notice: 'activity was successfully added.'
  end
  

  
  def mine_details
    # UserMailer.welcome(current_user).deliver
    # date for commitment marks
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
    @udpates = ActionLog.latest(current_user)
    
    @activity = Activity.find_by_id params[:id]
    if !@activity then
      return redirect_to :myp      
    end
    @commitment_marks = @activity.commitment_marks
    if (@activity.from_id) then
      @activity_from = Activity.find_by_id @activity.from_id
      if (@activity_from) then 
        if @activity_from.course_id then 
          @course = @activity_from.course
        else 
          @from_user_activity = @activity_from.user
        end
      else
        @course = nil
      end
    end
    @related_hals_activity = Hal.get_related_hals(@activity)
  end
  
end

app/helpers/strategies_helper.rb
module StrategiesHelper

  def shorten(text, length)
    stripped = ''
    stripped = strip_tags(text) if text
    return stripped if stripped.length < length
    ret = stripped.split(" ").each_with_object("") {|x,ob| break ob unless (ob.length + " ".length + x.length <= length);ob << (" " + x)}.strip
    ret += '...' if stripped.length > ret.length
  end
  
  def myp_status
    status = ''
  	if current_user.sign_in_count == 1
  	  status += "Welcome <strong>#{current_user.name}</strong>! <BR> We recommend you checkout the mini tutorial in the getting started menu.  It should take a couple minutes."
      # status += "Welcome <strong>#{current_user.name}</strong>!<BR>A sample course was added to your plan to give you an idea of the functionality.<BR>You might also want to click mini tutorial in getting started.  It should take a couple minutes.<BR>"
  	end
  	if current_user.strategy.current_activities.empty?
  		status += "If you want to #{link_to 'create a course, click here.', create_course_path}<BR><BR>"
  	end
    if current_user.strategy.current_activities.empty?
  		status += "Your plan is empty.  Would you like to:<BR>
  			#{link_to 'Add a course from here....', courses_path}<BR>
  			#{link_to 'Add and activity', add_activity_path}<BR>
  			Or see what other #{link_to 'users', users_path} are doing and add an activity from them <BR>"
    end
    if !current_user.strategy.current_activities.empty? and current_user.hals.empty? and  current_user.sign_in_count != 1
      status += "You can add a blog entry #{link_to 'here', new_hal_path}, or click on an activity and select 'Blog About'<BR>"
    end
    status
  end
  
end

app/views/strategies/_activity_cm.html.erb
<strong>Commitment marks:</strong><BR>
	<div id="calendar" class='table'>
	  <h3 id="month">
		<% if nav_month %>
			<%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d") %>
		    <%=h @date.strftime("%B %Y") %>
	    	<%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d") %>
		<% else %>
			<% @date =  Date.today %>
			<%=h @date.strftime("%B %Y") %>    
		<% end %>
	  </h3>
	  <%= calendar_for activity.commitment_marks, :year => @date.year, :month => @date.month do |calendar| %>
		<%= calendar.head('Sun','Mon', 'Tues', 'Wed', 'Thu', 'Fri', 'Sat') %>
	    <% calendar.day(:day_method => :done_date) do |date, cmss| %>
	      <%= date.day %>	<% for cm in cmss %>
			<%= image_tag("/images/check1.png", :height => '20')  %>
			<% break %>
			<% end %>
		
	      <ul>
			<table>
				<% for cm in cmss %>
				<!-- <tr bgcolor="aqua" height=2px><td>donex<%= image_tag("/images/check.png")  %></td></tr>				 -->
				<% end %>
			</table>
	      </ul>
	    <% end %>
	  <% end %>
	</div>

app/views/strategies/_plan_activity.html.erb
<% myp = (defined?(myp) and myp)? true : false %>

<div class='titleboxed'><%= link_to activity.title, activity %></div>
<div class="clear"></div><BR>
<% if activity.course and myp %> 
	<h3 class="float_lft">From course: <%= link_to activity.course.name, activity.course %> </h3>
	<div class="clear"></div><BR>
<% end %>
<% if !myp %>
	<%= link_to 'Add this activity to my plan', copy_activity_path(activity) %>
	<!-- TODO -->
<% end %>
<div class="show">
	<!-- for my plan: edit, delete, move in AS -->
	<% if myp %>	
	<div style='margin-left:auto; margin-right:auto;display:block;width:55%'>
		<div class="edit3a margin3" <% if first %>data-intro="You can blog about any activity.  Simply click here, enter your thoughts/feelings, or let your pet walk on the keyboard." data-step='10' <% end %>>
			<%= link_to "Blog about", new_hal_path(activity.id)  %>
		</div>
		<div class="edit3a margin3" <% if first %>data-intro="If you've committed to activities, it's nice to keep track of when you do them, especially recurring ones.  Whenever you do an activity mark it here.  You can see the calendar of when you've done them later" data-step='11' <% end %>> 			<%= link_to 'Did today', {:controller => "commitment_marks", :action => "add_commitment_mark_to_activity", :activity_id => activity.id}
			# , :remote => true 
			%>
		</div>
		</div>
	<div class="clear"></div>
	
		<% if activity.type == "ActivityInSequence" and activity.activity_sequence.has_previous? %>
			<%= link_to "<< previous", :controller => "ActivitySequences", :action => "set_previous", :id => activity.activity_sequence.id %>
		<% end %>

		<% if activity.type == "ActivityInSequence" and activity.activity_sequence.has_next? %>
			<%= link_to "next >>", :controller => "ActivitySequences", :action => "set_next", :id => activity.activity_sequence.id %>
		<% end %>
	<% end %>
	<!-- end for my plan: edit, delete, move in AS -->
<% if !activity.description.empty? %>
<div class='boxed'>
	<%= sanitize activity.description %>
</div>
<% end %>
<% if activity.customization and !activity.customization.empty? %> <p>How to customize in your plan: <%= activity.customization %></p><% end %>

<% timing = timing_text(activity); if !timing.empty? %>
<p><span class="bold">Timing:</span><%= timing %>
<BR></p>
<% end %>

	<div class="clear"></div>
	<% if myp and activity.commitment_marks.size > 0 %>
		<%= render :partial => 'strategies/activity_cm', locals: {activity: activity, nav_month: false} %>
		<%= link_to 'View All marks', mycms_path if myp %>
	<% elsif myp %>	
		You don't have any commitment marks for this activity.  
		<% if activity.kind_of_timing != "Reactive" %>Do it and <%= link_to 'log it!', :controller => "commitment_marks", :action => "add_commitment_mark_to_activity", :activity_id => activity.id %><% end %>	
	<% end %>
	<div class="clear"></div>


<% if myp and activity.type == "ActivityInSequence" and activity.activity_sequence.has_previous? %>
	<%= link_to "<< previous", :controller => "ActivitySequences", :action => "set_previous", :id => activity.activity_sequence.id %>
<% end %>

<% if myp and activity.type == "ActivityInSequence" and activity.activity_sequence.has_next? %>
	<%= link_to "next >>", :controller => "ActivitySequences", :action => "set_next", :id => activity.activity_sequence.id %>
<% end %>

<BR>

<% if myp %>	
	<div class="edit margin5" <% if first %>data-intro="You can modify all activities, whether you created them of they're from a course you joined.  This allows your plan to truly be yours." data-step='8'<% end %>>		
			<%= link_to "Edit", edit_activity_path(activity), :class=>"linkTwo", :style => 'float:right;background:#9DAAAA;' %>
		</div>				
		&nbsp;&nbsp;&nbsp;

	<div class="edit margin5" style='float:right;' <% if first %>data-intro="Another way to customize your plan is deleting activities, whether you created them or they're part of a course." data-step='9' <% end %>>
		<% if activity.type == "ActivityInSequence" %>
	       <%= link_to "Delete", activity.activity_sequence, confirm: 'This will delete all the activities in the sequence.  Are you sure?', method: :delete, :class=>"linkThree", :style => 'background:#9DAAAA;' %>
		<% else %>
	       <%= link_to "Delete", activity, confirm: 'This will delete the activity.  Are you sure?', method: :delete, :class=>"linkThree", :style => 'background:#9DAAAA;' %>
		<% end %>
		</div>
<% end %>

<div class="clear"></div>


									
	<% if activity.type == "ActivityInSequence" %>
		<% if activity.activity_sequence.activities.size < 50 %>
		<BR><b>Activities in the sequence:</b><BR>
			<% activity.activity_sequence.activities.each do |activity_in_sequence| %>
				<%= link_to activity_in_sequence.title, activity_in_sequence %>		&nbsp;<%= shorten(activity_in_sequence.description, 70) %>...<%= link_to 'see more', activity_in_sequence %>
				<% if myp and activity.activity_sequence.current_activity != activity_in_sequence %>
					<%= link_to "set as active", :controller => "ActivitySequences", :action => "make_current", :id => activity_in_sequence.activity_sequence.id, :activity_id => activity_in_sequence.id %>
				<% elsif myp %> << Current
				<% end %><BR>
			<% end %>
		<% else %>
			<%= link_to 'See all activities in this sequence', activity %>
		<% end %>
	<% end %>

<% if activity.hals.size > 0 %><h2>Entries:</h2><% end %>
	<% activity.hals.each do |hal| %>
		<div class="box_holder3 width100">
			<%= render :partial => 'hals/single_hal', locals: {hal: hal} %>					
		</div>
		<div class="clear"></div>
	<% end %>
</div>

app/views/strategies/_plan_activity_course_edit.html.erb
<div class="clear"></div>
<div class="show">
	<%= link_to 'Edit Activity', edit_activity_in_course_path(activity), :class => "bluebuttonpadded" %>
		<div class="edit_box" id="rightbar2">
            <div class="close"><a href="#"><img class="linkTwo" src="/images/close.png" alt=""></a></div>
		</div>
		<% if activity.type == "ActivityInSequence" %>
	       <%= link_to "Delete Activity", activity.activity_sequence, confirm: 'This will delete all the activities in the sequence.  Are you sure?', method: :delete, :class => "bluebuttonpadded" %>
		<% else %>
	       <%= link_to "Delete Activity", activity, confirm: 'This will delete the activity.  Are you sure?', method: :delete, :class => "bluebuttonpadded" %>
		<% end %>
	
		<div class="clear"></div><BR>
	
<h5><%= link_to activity.title, activity %></h5><BR>

<% if !activity.description.empty? %>
<div class='boxed'><%= sanitize activity.description %></div>
<% end %>
<% if !activity.customization.empty? %> <p>Customization: <%= activity.customization %></p><% end %>
<% if activity.kind_of_timing != "Other" %><p><span class="bold">Timing:</span><%= render :partial => 'strategies/timing', locals: {activity: activity} %> <% end %>
<BR></p>
	
	<% if activity.activity_sequence_id %>
		Activities in sequence:<BR>
		<ul id="activities" data-update-url="<%= sort_activity_sequences_url %>">
		 <% activity.activity_sequence.activities.each do |activity| %>		
			 <%= content_tag_for :li, activity do %>
				<span class="handle">[drag]</span>
				<%= link_to shorten(activity.title, 40), show_activity_path(activity) %>
		    	<%= link_to 'Edit', edit_activity_in_course_path(activity.id) %>
			    <%= link_to 'Delete', activity, confirm: 'Are you sure?', method: :delete %> 
			<% end %>
		<% end %>
		</ul>
		<BR>
		<%= link_to 'Add a sequential chapter', 	add_activity_to_sequence_path(activity.activity_sequence.activity_in_sequences.first) %>	
		<BR>	<%= link_to 'manage sequence', activity.activity_sequence %>
	<% else %>
		<BR>
		<%= link_to 'Add activity to sequence', add_activity_to_sequence_path(activity) %>	<BR>
		<%= link_to 'edit', edit_activity_in_course_path(activity) %> |
	    <%= link_to 'Delete', {:action => 'destroy', :controller => 'activities', :id => activity.id}, confirm: 'Are you sure?', method: :delete %>
	<% end %>

</div>

app/views/strategies/_timing.html.erb
<% if (defined?(labelled) and labelled and activity.kind_of_timing != "Other") %>
<strong>Timing:</strong>
<% end %>
<% case activity.kind_of_timing
	when "Frequency" %>	
		<% if activity.timing_expression %>
			<%= activity.timing_expression.split.first %> times per <%= activity.timing_expression.split.last %>
		<% else %>
			timing error
		<% end %>
	<% when "One time" %>
		Once
	<% when "Other" %>
	<% when "Whenever" %>
	<% when "Reactive" %>
		When "<%= activity.timing_expression %>."    
	<% else %>
		 -- error
<% end %>
<% if !activity.timing_duration.blank? and activity.course_activity? %>
until <%= activity.timing_duration %> from join
<% elsif activity.timing_until %>
before <%= activity.timing_until.strftime("%m/%d/%Y") %>
<% end %>

app/views/strategies/_view_activity.html.erb
<div class="float_rgt"><img src="/images/close.png" alt="close" title='<%= activity.id %>' class="linkOne closebtn">
</div>

<% if activity.type == "ActivityInSequence" and activity.activity_sequence.has_previous? %>
	<%= link_to "<< go to previous", :controller => "ActivitySequences", :action => "set_previous", :id => activity.activity_sequence.id %>
<% end %>

<% if activity.type == "ActivityInSequence" and activity.activity_sequence.has_next? %>
	<%= link_to "go to next >>", :controller => "ActivitySequences", :action => "set_next", :id => activity.activity_sequence.id %>
<% end %>

<BR>
<strong>Description</strong>: <%= sanitize activity.description %><BR>	
<BR>
<% if activity.from %> 
	Copied from: <%= link_to activity.from.title, activity.from  %> <BR>
<% end %>

<%= render :partial => 'shared/tag_display', locals: {tags: activity.tags} %>


<%= activity.type %>
<!-- ACT IN SEQ -->
<% if activity.type == "ActivityInSequence" %>
		<% activity_sequence = activity.activity_sequence %>
 		<% activity_sequence.activities.each do |activity| %>		
<% if activity_sequence.current_activity == activity %>>> Current <% end %>
		<%= activity.id %><%= link_to activity.title, show_activity_path(activity) %> - <%= render :partial => 'strategies/timing', locals: {activity: activity} %><BR>
		<% end %>
	<BR>
<% end %>
<!-- ACT IN SEQ -->


<% if activity.commitment_marks.size > 0 %>
	<%= render :partial => 'activity_cm', locals: {activity: activity} %><BR>
<% else %>	
	You don't have any commitment marks for this activity.  
	<% if activity.kind_of_timing != "Reactive" %>Do it and <%= link_to 'log it!', :controller => "commitment_marks", :action => "add_commitment_mark_to_activity", :activity_id => activity.id %><% end %>	
<% end %>

<%= render :partial => 'hals/hal_list', locals: {hals: activity.hals.first(3), show_user: false, commenting: false, title: "My Entries"} %>

<%= render :partial => 'hals/hal_list', locals: {hals: activity.related_hals.first(3), show_user: true, commenting: true, title: "Related Entries"}   if  activity.related_hals.size > 0 %>

<% if activity.hals.size > 1 or activity.related_hals.size > 3 %>
	<div class="edit padding10"><%= link_to "View more entries", show_activity_path(activity) %></div>
<% end %>

app/views/strategies/_view_one.erb
<% activty_map = get_activity_by_map(strategy.current_activities) %>
<% if activty_map.size > 0 %>
	<% activty_map.each do |key, activities| %>
		<div class="box_holder3 width100">
			<div class="title"><h3><%= key.nil? ? "none" : "Goal: " + key.title %><%= "-- from course " + key.course.name if key and key.course %></h3></div>
			<div class="box">
			<div class="goal">
		<% activities.each do |activity| %>
			<%= activity.id %><%= link_to activity.title, activity %> - <%= render :partial => 'strategies/timing', locals: {activity: activity} %>
			<div class="plus" id="<%= activity.id %>"><a href="#"><img src="/images/plus1.png" alt=""></a>
	            <div id="Details<%= activity.id %>" class="plus_details" style="display: none;">
	              <ul>
	                <li><%= link_to "Blog about", new_hal_path(activity.id)  %></li>
	                <li><%= link_to 'Did today', :controller => "commitment_marks", :action => "add_commitment_mark_to_activity", :activity_id => activity.id %></li>
					<li><%= link_to 'Edit', edit_activity_path(activity) %></li>
	                <li><%= link_to "Delete Activity", activity, confirm: 'This will delete the activity.  Are you sure?', method: :delete %></li>
	              </ul>
	            </div>
	          </div>
	
			<a href="#" onclick='return false;' class="linkOne", title='<%= activity.id %>'>view more</a>
			<div id="rightbar<%= activity.id %>" class="right_bar width97" style="margin-left:10px;">
				<%= render :partial => 'view_activity', locals: {activity: activity} %>
			</div>
	<BR>		
		<% end %>
		</div>
    </div>
	</div>
	<div class="clear"></div>

	<% end %>
<% else %>
	<% strategy.current_activities.each do |activity| %>
		<div class="box_holder3 border_btm">
			<div class="box">
			<% activities.each do |activity| %>
				<h2 class="bold"><%= activity.id %><%= link_to activity.title, myp_path(activity.id) %></h2>				
				<%= link_to image_tag("/images/checkmark.png", :size => "15x18", :title => "Did today"), :controller => "commitment_marks", :action => "add_commitment_mark_to_activity", :activity_id => activity.id %>&nbsp;&nbsp;
				<%= link_to image_tag("/images/delete_small.jpg", :size => "20x20", :title => "Delete Activity"), activity.becomes(Activity), confirm: 'This will delete the activity.  Are you sure?', method: :delete %>
				<%= link_to "add entry about", new_hal_path(activity.id)  %>
			<% end %>
			</div>
		</div>
		<div class="clear"></div>
	<% end %>
<% end %>