config/routes.rb
Opp::Application.routes.draw do
   
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "messages_controller/new"
  get "messages_controller/create"

  resources :activity_sequences
  resources :activity_in_sequences

  mount Ckeditor::Engine => '/ckeditor'

  get "hals/view(/:tab)", to: 'hals#view', as: 'view_hals'
  get "hals/view/1", to: 'hals#view', as: 'hals_my_insights'
  get "hals/view/2", to: 'hals#view', as: 'hals_following'
  get "hals/view/3", to: 'hals#view', as: 'hals_my_courses'
  get "hals/view/4", to: 'hals#view', as: 'hals_all_hals'
  get "hals/view/5", to: 'hals#view', as: 'hals_help_wanted'
  get "hals/view/0", to: 'hals#view', as: 'hals_mine'
  
  get "courses/:id/4", to: 'courses#show', as: 'course_people'
  get "hals/edit/:id", to: 'hals#edit', as: 'edit_hal'
  get "hals/new_hal(/:id)", to: 'hals#new_hal', as: 'new_hal'

  resources :hals
  
  
  resources :activities, :collection => { :sort => :post }
  get "activity_sequences/sort", to: "activity_sequences#sort", as: 'sort_activity_sequences'
  get "activities/copy_activity/:id", to: "activities#copy_activity", as: 'copy_activity'

  get "activities/sort", to: "activities#sort", as: 'sort_activities'
  get "activities/show/:id", to: "activities#show", as: 'show_activity'
  get "activities/new", to: "activities#new",  as: 'add_activity'
  get "activity_in_sequences/add_to_sequence/:id", to: "activity_in_sequences#add_to_sequence",  as: 'add_activity_to_sequence'
  
  get "activities/add_activity_to_course/:id", to: "activities#add_activity_to_course",  as: 'add_activity_to_course'
  get "activities/edit_activity_in_course/:id", to: "activities#edit_activity_in_course",  as: 'edit_activity_in_course'
  
  post "activities/create_activity_in_course/:id", to: "activities#create_activity_in_course",  as: 'create_activity_in_course'
  get "strategies/copy_activity/:id", to: "strategies#copy_activity",  as: 'copy_activity'

  get "activities/mine", to: "strategies#mine",  as: 'user_strategy'
  get "strategies/mine?tut=true", to: 'strategies#mine', as: 'tut'  
  get "strategies/mine(/:id)", to: 'strategies#mine', as: 'myp'
  get "strategies/mine_details/:id", to: 'strategies#mine_details', as: 'mypd'

  get "commitment_marks", to: 'commitment_marks#mycms', as: 'mycms'

  get "courses/new", to: 'courses#new', as: 'create_course'
  get "courses/my_created", to: 'courses#my_created', as: 'my_created_courses'
  get "courses/new", to: 'courses#new', as: 'create_course'
  get "courses/my_created", to: 'courses#my_created', as: 'my_created_courses'
  get "courses/update_description/:id", to: 'courses#update_description', as: 'update_description'
  get "courses/publish_course/:id", to: 'courses#publish_course', as: 'publish_course'
  get "courses/edit_course/:id(/:tab)/(:actvitiy_id)", to: 'courses#edit_course', as: "edit_course"
  get "courses/edit_course/:id/0", to: 'courses#overview_edit', as: 'course_overview_edit'
  get "courses/edit_course/:id/1/(:actvitiy_id)", to: 'courses#edit_course', as: 'course_plan_edit'
  get "courses/edit_course/:id/2", to: 'courses#description_edit', as: 'course_description_edit'
  get "courses/:id(/:tab)", to: 'courses#show', as: 'show_course'
  get "courses/:id/4", to: 'courses#show', as: 'course_people'
  get "courses/:id/3", to: 'courses#show', as: 'course_blogs'
  get "courses/:id/2", to: 'courses#show', as: 'course_description'
  get "courses/:id/1", to: 'courses#show', as: 'course_plan'
  get "courses/:id/0", to: 'courses#show', as: 'course_overview'
  resources :courses
  

  match "share_course_on_fb/:id", to: "courses#share_course_on_fb", as: "share_course_on_fb"

  get "banner", to: 'info#banner', as: 'bann'
  get "about_us", to: 'info#about', as: 'about'
  get "eula", to: 'info#eula', as: 'eula'
  get "privacy", to: 'info#privacy', as: 'privacy'
  get "howitworks", to: 'info#howitworks', as: 'howitworks'
  get "gettingstartedcreate", to: 'info#gettingstartedcreate', as: 'gettingstartedcreate'
  get "gettingstartedoverview", to: 'info#gettingstartedoverview', as: 'gettingstartedoverview'

  get "contact_us", to: 'messages#new', as: 'contact_us'
  match "newsletter", to: 'messages#news', as: 'newsletter'
  resources :messages

  match "add_commitment_mark_to_activity/:activity_id", :controller => "commitment_marks", :action => "add_commitment_mark_to_activity"

  match 'my_plan/:id',  :controller => "strategies", :action => "mine", :activity_id => :id

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  ActiveAdmin.routes(self)
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new", as: 'signin'
    get "sign_out", :to => "devise/sessions#destroy" #destroy_user_session"
  end  # devise_for :users
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => 'registrations'}
  ActiveAdmin.routes(self)
  ActiveAdmin.routes(self)

  match 'auth/:provider/callback', to: 'sessions#create'
  
  match 'auth/facebook/callback?error', to: redirect('/')
  match 'auth/facebook/callback?error_code', to: redirect('/')
  
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
    
  get 'users/follow_user/:id',:to => 'users#follow_user', as: 'follow'
  match 'users/login_or_signup',  :controller => "users", :action => "login_or_signup"
  match 'users/myprofile',  :controller => "users", :action => "myprofile", :as => "my_profile"
  match 'users/editmyprofile',  :controller => "users", :action => "edit_profile", :as => "edit_profile"

  resources :users do
    member do
      put :follow
      put :unfollow
    end
  end
  
  
  resources :comments

  match 'join_course/:id',  :controller => "courses", :action => "join", :as => "join_course"

  match 'co',  :controller => "courses", :action => "index"
  root :to => "home#index"
 
  

  match ':controller(/:action(/:id))(.:format)'
  
  
  
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!, :except =>[:show]
  before_filter :require_owner, :only =>[:edit, :update, :destroy]


  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])
    @hals = @activity.hals
    @related_hals = Hal.get_related_hals(@activity)
    @date = params[:month] ? Date.parse(params[:month]) : Date.today    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # sort list of actiities in strategy   => TODO optimize
  def sort
    params[:activity].each_with_index do |id, index|
      activity = Activity.find_by_id(id)
      Activity.update_all(['position=?', index+1], ['id=?', id]) unless activity.user_id != current_user.id
    end
    render :nothing => true
  end
  
  def copy_activity
    @activity = Activity.find_by_id(params[:id])
    @activity.copy_to_user(current_user)
    redirect_to :back, notice: 'Activity copied'      
  end
  
  def add_to_sequence
    @seq_activity = Activity.find_by_id(params[:id])
    @activity = Activity.new
    if (!@seq_activity || @seq_activity.user != current_user)
      redirect_to @activity, notice: 'Not yours.  Pas touche.  || dunt exist'      
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new
    @activity.until_radio = 'no_date'

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end
  
  # Add a new activity to a course user has created
  def add_activity_to_course
    @activity = Activity.new
    # @activity.until_radio = 'no_date'
    @course = Course.find_by_id(params[:id])
    if (!@course || @course.user != current_user)
      redirect_to @course, notice: 'Not yours.  Pas touche.  || dunt exist'      
    end
  end
  
  # Add a new activity to a course user has created
  def edit_activity_in_course
    @activity = Activity.find(params[:id])
    @course = @activity.strategy.course
    if (!@course || @course.user != current_user)
      redirect_to @course, notice: 'Not yours.  Pas touche.  || dunt exist'      
    end    
  end
  

  def create_activity_in_course
    @activity = Activity.new(params[:activity])
    puts "duration: #{@activity.duration_unit}"
    puts "duration num: #{@activity.duration_number}"
    @course = Course.find_by_id(params[:course_id])
    if !@activity.new_goal_text.empty?
      goal = @course.strategy.create_or_use_goal(@activity.new_goal_text)
      @activity.goal_id = goal.id
    end
    if (@course.user_id != current_user.id)   # TODO do better?
      redirect_to :myp, :notice => "not yours"
      return
    end
    @course.add_activity(@activity)
    @activity.user_id = current_user.id
    
    ActionLog.log_other(current_user.id, "update", @course)  if @course.published?
    
    respond_to do |format|
      if @activity.save
          # log action
          ActionLog.log_update(@course)         
          format.html { redirect_to course_plan_edit_path(@course.id), notice: 'Activity was successfully created.' }
      else
          format.html { render action: "add_activity_to_course" }
          format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end    
  end


  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
    redirect_to @activity, notice: 'No way, not yours.'  if (@activity.user_id != current_user.id)
  end
  

  # POST /activities
  # POST /activities.json
  # create activity for a user's plan
  def create
    # debugger
    @activity = Activity.new(params[:activity])
    # jquery dp hack
    until_date = params[:activity][:timing_until]
    @activity.timing_until = Date.strptime(until_date, "%m/%d/%Y") if !until_date.blank?
    course_id = params[:course_id]    
    @activity.strategy = current_user.strategy
    @activity.user_id = current_user.id
    # create new goal if new_goal_text filled in
    if !@activity.new_goal_text.empty?
      goal = current_user.strategy.create_or_use_goal(@activity.new_goal_text)
      @activity.goal_id = goal.id
    end
    
    # log creation
    ActionLog.log_create(@activity)             
    
    respond_to do |format|
      if @activity.save
        ActionLog.log_create(@activity)                 
        if params[:seq_activity]
          format.html { redirect_to activity_sequence_path(@activity.activity_sequence_id), notice: 'Activity was successfully created.' }          
        else
          format.html { redirect_to myp_path(@activity), notice: 'You have a new activity in your plan.' }
        end
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])
    # add new goal if entered
    new_goal_text = params[:activity][:new_goal_text]
    if !new_goal_text.empty?
      goal = @activity.strategy.create_or_use_goal(new_goal_text)
      @activity.goal_id = goal.id
      params[:activity][:goal_id] = @activity.goal_id  # hack for the update_attributes later
    end
    
    # log update activity
    if (@activity.strategy and @activity.strategy.class.name == "CourseStrategy")
      @course = @activity.strategy.course
      ActionLog.log_other(current_user.id, "update", @course)  if @course.published?
    else
      ActionLog.log_update(@activity)             
    end    
    

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        if @activity.myp_activity?
          format.html { redirect_to myp_path(@activity), notice: 'Activity was successfully updated.' }
          format.json { head :no_content }
        elsif @activity.course_activity?
          format.html { redirect_to course_plan_edit_path(@activity.strategy.course), notice: 'Activity was successfully updated.' }
          format.json { head :no_content }          
        else 
          format.html { redirect_to root_path, notice: 'Activity was successfully updated.' }
          format.json { head :no_content }          
        end
      else
        flash[:error] = "Some errors occured - Activity Could not be saved"
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])

    # log deletion
    if (@activity.strategy and @activity.strategy.class.name == "CourseStrategy")
      ActionLog.log_other(current_user.id, "update", @course)  if @activity.strategy.course.published?
    else
      ActionLog.log_destroy(@activity)             
    end    

    @activity.destroy
    
    respond_to do |format|
      format.html { redirect_to :back, notice: "The activity has been deleted" }
      format.json { head :no_content }
    end
  end
  
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper


  def get_activity_by_goal_or_course(activities, show_course = true)
    keys = activities.pluck('goal_id').uniq
    return_hash = Hash.new
    # if activities with no course, no goal
    return_hash[nil] = activities.find_all {|a| a if a.goal_id== nil and a.course_id == nil} if show_course
    return_hash[nil] = activities.find_all {|a| a if a.goal_id== nil } if !show_course
    # if no courseless goalless activities were found, remove nil key
    return_hash.delete_if{|k,v| k==nil and v==[]}
    
    # for other activities
    keys.each do |key|
      g = Goal.find_by_id key
      if (g)
        index = g.title
        index +=' - Course: ' + g.course.name if g.course and show_course
        return_hash[index] = activities.find_all {|a| a['goal_id'] == key}
      else 
        # no goal, but course
        acts = activities.find_all {|a| a['goal_id'] == key}  # should be nil goal
        return_hash.merge!(acts.group_by {|act| 'course: ' + act.course.name if act.course and show_course })        
      end
    end
    return_hash
  end

  
  # organize activities in hash by => list of acts
  def get_activity_by_map(activities, by="goal_id")
    keys = activities.pluck(by).uniq
    return_hash = Hash.new
    keys.each do |key|
      g = Goal.find_by_id key
      return_hash[g] = activities.find_all {|a| a[by] == key}
    end
    return_hash
  end
  
  # return all goals in a specific strategy (nil ommitted)
  def get_goals_for_strategy(strategy)
    keys = strategy.activities.pluck('goal_id').uniq
    if (keys != [nil])
      Goal.find(keys)
    else 
      # no goals
      []
    end
  end


  def get_goal_collection_for_course(course_id) 
    Goal.where(course_id: course_id).pluck(:title)
  end
  
  def timing_text(activity)
    return_text = ''
    case activity.kind_of_timing
    	when "Frequency"
      		if activity.timing_expression 
    			  return_text = activity.timing_expression.split.first +  " times per " + activity.timing_expression.split.last
      	  else 
      			return_text = "timing error"
    		 end
    	 when "One time"
    		 return_text = "Once"
    	 when "Other" 
    	 when "Whenever" 
    	 when "Reactive" 
    	   if activity.timing_expression
    		   return_text = "When " +  activity.timing_expression    
  		   else
  		     return_text = 'Reactive'
  		   end
    	 else 
    		 return_text = "error"
    end 
    if !activity.timing_duration.blank? and activity.course_activity? 
      return_text += "until "  + activity.timing_duration + "from join"
    elsif activity.timing_until 
      return_text = "before "  +  activity.timing_until.strftime("%m/%d/%Y") 
    end 
    return_text    
  end
  
end

app/views/activities/_activity_commitment_marks.html.erb
<div id="calendar">
  <h2 id="month">
	<%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d") %>
    <%=h @date.strftime("%B %Y") %>
    <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d") %>
  </h2>
  <%= calendar_for @activity.commitment_marks, :year => @date.year, :month => @date.month do |calendar| %>
	<%= calendar.head('Sunday','Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
    <% calendar.day(:day_method => :done_date) do |date, cmss| %>
      <%= date.day %>
      <ul>
		<table>
			<% for cm in cmss %>
			<tr bgcolor="<%= convert_string_to_hex(@activity.title) %>" height=2px><td></td></tr>

			<% end %>
		</table>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/activities/_activity_in_course_form.html.erb
<%= semantic_form_for @activity.becomes(Activity), :url => url, :html => {:class => "course_manage"} do |f| %>
<% if @activity.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

    <ul>
    <% @activity.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

	<%= hidden_field_tag 'course_id', @course.id %>
	<div class="row">	
		<label>The title as it will appear in the plan</label><%= f.text_field :title %>
		<div class="clear"></div>	
	</div>

	<div class="row">	
		<label>Customization information <%= tipper("If you would like followers of this activity to modify this, enter how here (e.g. 'This activity is part of the workout activities.  Only keep one.  Delete this if you've picked another. You can also have instructions in the description, but this will appear in the Plan view.") %></label><%= f.text_area :customization %>
		<div class="clear"></div>	
	</div>


	<div class="row">
		<label>Goal<%= tipper("What are we trying to achieve by doing this activity?  This can be left blank.") %></label>
		<% if get_goals_for_strategy(@course.strategy) != [] %>
			<%= f.input :goal,  :collection => 
get_goals_for_strategy(@course.strategy).concat([Goal.new(:id => 0, :title => 'Create a New Goal')]),
 :prompt => "Select a Goal", :label => false  %>
			<div class="clear"></div><BR>		
			<%= label :goal, "New goal text",:id => "goal_new_text", :style=>"display:none;" %>
			<%= f.text_field :new_goal_text, :style=>"display:none;" %>
		<% else %>
		<%= f.text_field :new_goal_text %>
		<% end %>
		<div class="clear"></div>
	</div>

	<BR>
		
	<div class="boxed">
		<label>Timing <%= raw tipper_text("Enter how people should tackle this activity:
		- a one time thing
		- an activity to do in reaction to something (e.g. when I feel hunger strike; when I'm irrate)
		- an activity to do repeatedly at a set frequency (e.g. 3 times per week)
		- an activity to be done whenever (user discretion)") %></label>
		<div class="clear"></div>
		<div class="row">
		<%=   f.input :kind_of_timing,  :as => :select,      :collection => ["Other", "One time", "Reactive", "Frequency"], :default => "Other" %>
		</div>
		<div class="clear"></div>

		<div class="row">
			<div id='freak'>
				<label>Timing Frequency</label><%= f.text_field :freak_number, :style=>"width:50px; margin-right:10px;" %>&nbsp; Times per &nbsp;&nbsp;<%= f.select :freak_interval, ["Day", "Week", "Month"], {}, {:style => 'width:100px'}%>
			</div>
		</div>

		<div class="row">
			<div id='react'>
				<label>When the following occurs:</label><%= f.text_field :reactive_expression %>
			</div>
		</div>
		<div class="clear"></div>

		<div class="row">
			<label>Until?</label>
			<table>
				<tr>
					<td></td>
					<td><%= f.radio_button :until_radio, "nodate" %>	
							<%= label :until_radio, "No end point" %>
					</td>
					<td><%= f.radio_button :until_radio, "date" %>
						<%= label :until_radio, "Set duration" %>					
					</td>
				</tr>
			</table>
		</div>
		<div class="clear"></div>
		<div id='untilfield' <% if @activity.until_radio == 'nodate' %>style="display:none;" <% end %>>
			<BR>
			<div class="clear"></div>
			<BR>
			<label>Duration <%= tipper("If this activity should have a duration, i.e. 'Do it for 3 weeks.'  If this activity is ongoing or at the discretion of the user, set to 'no end date'") %></label>	
			<%= f.text_field :duration_number, :style => "width:40px" %> &nbsp;&nbsp;
			<%= f.select :duration_unit, ["Days", "Weeks", "Months", "Years"], {}, {:style => 'width:100px'} %> after start.
		</div>
		</div>
		<div class="clear"></div>
	
	<div class="row">
		<label>Description<%= tipper(" Add all details relevant.  We recommend adding other media to complement the text (external links, pictures, videos)") %></label>
		<div class="clear"></div>
    	<%= f.text_area :description, :class => 'ckeditor' %>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>

		
	<div class="row">
		<label>Tag List<%= tipper("Comma separated tags for this activity (e.g. 'weight loss, exercise')") %></label><%= f.input  :tag_list, :label => false%>
		<div class="clear"></div>
	</div>
	
	<div class="row">
		<%= f.submit %>
		<%= submit_tag 'Cancel', :name => 'cancel' %>
		<div class="clear"></div>
	</div>

<% end %>

app/views/activities/add_activity.html.erb
<% @title = "Add Activity" %>
<% @show_aside = true %>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/activities/add_activity_to_course.html.erb
<% @title = "Add an Activity to #{@course.name}" %>
<% @show_aside = true %>

<%= render :partial => 'activity_in_course_form', locals: {url: create_activity_in_course_path} %>

app/views/activities/edit.html.erb
<% @title = "Edit #{@activity.title}" %>
<% @show_aside = true %>

	<%= render 'form' %>

app/views/activities/edit_activity_in_course.html.erb
<%= addcustomjs 'ckeditor/init' %>
<%= addcustomjs 'ckeditor/config' %>
<%= addcustomjs 'activities' %>

<% @show_aside = true %>
<% @title = "Edit activity #{@activity.title}" %>


<%= render :partial => 'activity_in_course_form', locals: {url: activity_path(@activity)} %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<% @title = "New activity" %>
<% @show_aside = true %>

	<%= render 'form' %>

app/views/activities/show.html.erb
<% @title = @activity.title %>
<% @title += " from course " + @activity.course.name if @activity.course %>
<% @show_aside = true %>


<div class="tab_holder">
  <div id="tabs">
    <div id="tabs-1" style="overflow:hidden;">


<% if (current_user && (@activity.user_id == current_user.id)) then %>
<BR>
	<%= link_to 'Blog about it', new_hal_path(@activity.id), :class => 'bluebuttonpadded' %> &nbsp;
		<%= link_to 'Did today', {:controller => "commitment_marks", :action => "add_commitment_mark_to_activity", :activity_id => @activity.id}, :class => 'bluebuttonpadded' %> &nbsp;
		<%= link_to 'Edit', edit_activity_path(@activity), :class => 'bluebuttonpadded' %> &nbsp;
	    
			<% if @activity.type == "ActivityInSequence" %>
		       <%= link_to "Delete", @activity.activity_sequence, confirm: 'This will delete all the activities in the sequence.  Are you sure?', method: :delete, :class=>"bluebuttonpadded", :style => 'background:#9DAAAA;' %>
			<% else %>
		       <%= link_to "Delete", @activity, confirm: 'This will delete the activity.  Are you sure?', method: :delete, :class=>"bluebuttonpadded" %>
			<% end %>
<% end %>

<div class="clear"></div><BR>
<% if @activity.strategy and @activity.strategy.course %>
Part of course <%= link_to @activity.strategy.course.name, @activity.strategy.course %><BR>
<% elsif @activity.user and !@activity.activity_sequence_id and @activity.user != current_user %>
In <%= link_to @activity.user.name, @activity.user %>'s plan
<% end %>
<BR>
<% if @activity.goal_id %>
<strong>Goal: </strong><%= @activity.goal.title %>
<% end %>
<BR>
	<% timing = timing_text(@activity); if !timing.empty? %>
	<p><span class="bold">Timing:</span><%= timing %>
	<BR></p>
	<% end %>
	
<% if !@activity.description.empty? %>
<div class='boxed'>
<%= sanitize @activity.description %>
</div>
<% end %>
<BR>
<%= render :partial => 'shared/tag_display', locals: {tags: @activity.tags} %>
<BR>
<% if @activity.from %> Copied from: <%= link_to @activity.from.title, @activity.from  %> <% end %>

		<div class="clear"></div>
		<% if @activity.myp_activity? and @activity.commitment_marks.size > 0 %>
			<%= render :partial => 'strategies/activity_cm', locals: {activity: @activity, nav_month: true} %><BR>
		<% elsif @activity.myp_activity? %>	
			You don't have any commitment marks for this activity.  
			<% if @activity.kind_of_timing != "Reactive" %>Do it and <%= link_to 'log it!', :controller => "commitment_marks", :action => "add_commitment_mark_to_activity", :activity_id => @activity.id %><% end %>	
		<% end %>


<% if @activity.type == "ActivityInSequence" %>
	<BR><b>Activities in the sequence:</b><BR>
		<ul>
		<% @activity.activity_sequence.activities.each do |activity_in_sequence| %>
			<li><%= link_to activity_in_sequence.title, activity_in_sequence %>&nbsp;<%= shorten(activity_in_sequence.description, 50) %>
			<% if @activity.activity_sequence.current_activity != activity_in_sequence and activity_in_sequence.user == current_user and @activity.myp_activity? %>
			<%= link_to "set as active", :controller => "ActivitySequences", :action => "make_current", :id => activity_in_sequence.activity_sequence.id, :activity_id => activity_in_sequence.id %>
			<% elsif activity_in_sequence.user == current_user and @activity.myp_activity? %> << Current
			<% end %>
			</li>
		<% end %>
		</ul>
		<%= link_to 'Manage Sequence', @activity.activity_sequence %>
<% end %>

<div class="clear"></div><BR>
<div class="clear"></div><BR>

<% if @hals.size > 0 %>
	<b>Your Entries:</b><BR>
<% end %>
<%= render :partial => 'hals/hal_list', locals: {hals: @hals, title: 'Your Entries', show_user: false} %>


<div class="clear"></div><BR>
<% if @related_hals.size > 0 %>
	<BR>
	<b>Related Entries:</b>
	<BR>
	<% @related_hals.each do |hal| %>
		<div class="box">
			<%= render :partial => 'hals/single_hal', locals: {hal: hal} %>					
		</div>
	<% end %>
<% end %>

</div>
</div>
</div>