config/routes.rb
Opp::Application.routes.draw do
   
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "messages_controller/new"
  get "messages_controller/create"

  resources :activity_sequences
  resources :activity_in_sequences

  mount Ckeditor::Engine => '/ckeditor'

  get "hals/view(/:tab)", to: 'hals#view', as: 'view_hals'
  get "hals/view/1", to: 'hals#view', as: 'hals_my_insights'
  get "hals/view/2", to: 'hals#view', as: 'hals_following'
  get "hals/view/3", to: 'hals#view', as: 'hals_my_courses'
  get "hals/view/4", to: 'hals#view', as: 'hals_all_hals'
  get "hals/view/5", to: 'hals#view', as: 'hals_help_wanted'
  get "hals/view/0", to: 'hals#view', as: 'hals_mine'
  
  get "courses/:id/4", to: 'courses#show', as: 'course_people'
  get "hals/edit/:id", to: 'hals#edit', as: 'edit_hal'
  get "hals/new_hal(/:id)", to: 'hals#new_hal', as: 'new_hal'

  resources :hals
  
  
  resources :activities, :collection => { :sort => :post }
  get "activity_sequences/sort", to: "activity_sequences#sort", as: 'sort_activity_sequences'
  get "activities/copy_activity/:id", to: "activities#copy_activity", as: 'copy_activity'

  get "activities/sort", to: "activities#sort", as: 'sort_activities'
  get "activities/show/:id", to: "activities#show", as: 'show_activity'
  get "activities/new", to: "activities#new",  as: 'add_activity'
  get "activity_in_sequences/add_to_sequence/:id", to: "activity_in_sequences#add_to_sequence",  as: 'add_activity_to_sequence'
  
  get "activities/add_activity_to_course/:id", to: "activities#add_activity_to_course",  as: 'add_activity_to_course'
  get "activities/edit_activity_in_course/:id", to: "activities#edit_activity_in_course",  as: 'edit_activity_in_course'
  
  post "activities/create_activity_in_course/:id", to: "activities#create_activity_in_course",  as: 'create_activity_in_course'
  get "strategies/copy_activity/:id", to: "strategies#copy_activity",  as: 'copy_activity'

  get "activities/mine", to: "strategies#mine",  as: 'user_strategy'
  get "strategies/mine?tut=true", to: 'strategies#mine', as: 'tut'  
  get "strategies/mine(/:id)", to: 'strategies#mine', as: 'myp'
  get "strategies/mine_details/:id", to: 'strategies#mine_details', as: 'mypd'

  get "commitment_marks", to: 'commitment_marks#mycms', as: 'mycms'

  get "courses/new", to: 'courses#new', as: 'create_course'
  get "courses/my_created", to: 'courses#my_created', as: 'my_created_courses'
  get "courses/new", to: 'courses#new', as: 'create_course'
  get "courses/my_created", to: 'courses#my_created', as: 'my_created_courses'
  get "courses/update_description/:id", to: 'courses#update_description', as: 'update_description'
  get "courses/publish_course/:id", to: 'courses#publish_course', as: 'publish_course'
  get "courses/edit_course/:id(/:tab)/(:actvitiy_id)", to: 'courses#edit_course', as: "edit_course"
  get "courses/edit_course/:id/0", to: 'courses#overview_edit', as: 'course_overview_edit'
  get "courses/edit_course/:id/1/(:actvitiy_id)", to: 'courses#edit_course', as: 'course_plan_edit'
  get "courses/edit_course/:id/2", to: 'courses#description_edit', as: 'course_description_edit'
  get "courses/:id(/:tab)", to: 'courses#show', as: 'show_course'
  get "courses/:id/4", to: 'courses#show', as: 'course_people'
  get "courses/:id/3", to: 'courses#show', as: 'course_blogs'
  get "courses/:id/2", to: 'courses#show', as: 'course_description'
  get "courses/:id/1", to: 'courses#show', as: 'course_plan'
  get "courses/:id/0", to: 'courses#show', as: 'course_overview'
  resources :courses
  

  match "share_course_on_fb/:id", to: "courses#share_course_on_fb", as: "share_course_on_fb"

  get "banner", to: 'info#banner', as: 'bann'
  get "about_us", to: 'info#about', as: 'about'
  get "eula", to: 'info#eula', as: 'eula'
  get "privacy", to: 'info#privacy', as: 'privacy'
  get "howitworks", to: 'info#howitworks', as: 'howitworks'
  get "gettingstartedcreate", to: 'info#gettingstartedcreate', as: 'gettingstartedcreate'
  get "gettingstartedoverview", to: 'info#gettingstartedoverview', as: 'gettingstartedoverview'

  get "contact_us", to: 'messages#new', as: 'contact_us'
  match "newsletter", to: 'messages#news', as: 'newsletter'
  resources :messages

  match "add_commitment_mark_to_activity/:activity_id", :controller => "commitment_marks", :action => "add_commitment_mark_to_activity"

  match 'my_plan/:id',  :controller => "strategies", :action => "mine", :activity_id => :id

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  ActiveAdmin.routes(self)
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new", as: 'signin'
    get "sign_out", :to => "devise/sessions#destroy" #destroy_user_session"
  end  # devise_for :users
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => 'registrations'}
  ActiveAdmin.routes(self)
  ActiveAdmin.routes(self)

  match 'auth/:provider/callback', to: 'sessions#create'
  
  match 'auth/facebook/callback?error', to: redirect('/')
  match 'auth/facebook/callback?error_code', to: redirect('/')
  
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
    
  get 'users/follow_user/:id',:to => 'users#follow_user', as: 'follow'
  match 'users/login_or_signup',  :controller => "users", :action => "login_or_signup"
  match 'users/myprofile',  :controller => "users", :action => "myprofile", :as => "my_profile"
  match 'users/editmyprofile',  :controller => "users", :action => "edit_profile", :as => "edit_profile"

  resources :users do
    member do
      put :follow
      put :unfollow
    end
  end
  
  
  resources :comments

  match 'join_course/:id',  :controller => "courses", :action => "join", :as => "join_course"

  match 'co',  :controller => "courses", :action => "index"
  root :to => "home#index"
 
  

  match ':controller(/:action(/:id))(.:format)'
  
  
  
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def about
  end

  def howitworks
    
  end
  
  def gettingstartedoverview
    
  end
  
  def banner
    render :layout => 'banner'
  end

  def gettingstartedcreate
    
  end

  def eula
    
  end
  
  def privacy
    
  end

end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/about.html.erb
<% @title = "About us" %>

		Blah di blah

app/views/info/gettingstartedcreate.html.erb
<% @title = "Getting Started - Create a course" %>

<div class='boxed'>
	<div class="clear"></div>
	<BR>
You can create a course by going to <%= link_to 'create a course', create_course_path %>.
<BR><BR>
Enter all the information in the overview and then create a plan.  This will consist of one or more activities.  You can look at the <%= link_to "listed courses", courses_path %> for examples of plans.
<BR><BR>
The <strong>activities</strong> can be all at the same time (e.g. <%= link_to "The Four Agreements", 'http://www.melearni.ng/courses/14' %> where you abide to each agreement hopefully in every moment), or sequential (e.g. <%= link_to "the 8 week beginner's running program", "http://www.melearni.ng/courses/16" %> or <%= link_to "A Course In Miracles", "http://www.melearni.ng/courses/15" %> where you focus on an activity before moving to the next).
<BR>
	Activities can be
	<ul>
		<li>Reactive:  In reaction to something external or internal.  For example journal when I feel angry</li>
		<li>Frequency:  Do something a few times per time period.  For example do a new activity of <%= link_to "A Course In Miracles", "http://www.melearni.ng/courses/15" %> each day.  Or run 3 times per week.</li>
		<li>One time:  If it's something to do once and you're done.  For example "Create a meal plan" in a weight loss course.</li>
		<li>Other:  Anything that doesn't fall into one of the previous.</li>
	</ul>

<BR>
The details section of the course is where you can add all extra information you'd like people to see.  Since it won't be in their plan they won't see it regularly though.  You can be as lengthy as you'd like here.
<BR>
	
<BR>
	<strong>Publishing a course</strong><BR>
		Once you're comfortable with your course you can publish it, which means you can then invite others to join it.  It will also send a request to be listed on the site.  Send people the URL of your course when you invite them.  You can continue changing the contents of your course after it's published.  Even after people have joined it.  Just keep in mind people will not see the updates to the activities in their plan as those were copied earlier.  <BR>
			
<BR>
	<strong>Blogs</strong><BR>
		We recommend you check the blog posts, specifically when people have checked 'help.'  You can comment on their entries to provide any insights that would be helpful.
<BR>	
</div>

app/views/info/gettingstartedoverview.html.erb
<% @title='Getting Started' %>

<div class='boxed'>


<p style="font-family:serif; font-size:16px">As a member of meLearning you have a <strong><%= link_to "plan", :myp %></strong> with <strong>activities</strong> in it.</p>

<p style="font-family:serif; font-size:16px">You either have a simple tutorial course or a course you joined in your plan.<br /><br />
<strong><span style="font-family:serif; font-size:18px">What to do with these activities?</span></strong></p>

<ul>
	<li><strong>Mark as done</strong>: &nbsp;Whether it's a recurring activity or a one time thing, you can mark any activity as &quot;done today.&quot; &nbsp;You can then see when you've done them and how you're holding up to your commitment to yourself. &nbsp;Whether your activity is &quot;Run every morning&quot; or &quot;Eat the best chocolate you can get your hands on when upset,&quot; mark it every time you do it.</li>
	<li><strong>Modify</strong>: &nbsp;Change them to suit your individual situation if that's applicable. &nbsp;For instance if you have an activity to run three times a week, but you only want to commit to twice a week, set the new frequency. &nbsp;You can change the title, the description or any other field; it will still be linked to the original and others with that activity can see your blog entries and vice versa.</li>
	<li><strong>Blog</strong>: &nbsp;Write entries about your activities when you've done them or feel like writing something (such as: &quot;I can't get off the couch and run&quot; or &quot;I'm no longer sore the day after a run&quot;). &nbsp;You can view all your blog entries <%= link_to 'here', :view_hals %>. &nbsp;Whenever you have insights you want to record, write that in the insight field. &nbsp;Later you can see all of your insights in one <%= link_to "place", :hals_my_insights %> . &nbsp;If you're struggling with anything you can check &quot;help requested.&quot;</li>
	<li><strong>Check out</strong>: &nbsp;How are others doing with these activities or how have they modified them? &nbsp;You can see blog entries for your courses in the <%= link_to 'course blogs section', :hals_my_courses %></li>
	<li><strong>Help Others</strong>: &nbsp;If others have written blog entries about an activity you have in your plan you'll see them when you view that activity. &nbsp;If they're confused or struggling you'll see the help wanted sign. &nbsp;Feel free to offer any guidance or encouragement you can provide in the comments. &nbsp;In the <%= link_to 'blogs help requested section', :hals_help_wanted %> you can also see everyone requesting guidance.</li>
</ul>

<p style="font-family:serif; font-size:16px"><br />
<span style="font-family:serif; font-size:18px"><strong>Add activities for yourself</strong></span><br />
&nbsp;&nbsp;&nbsp;&nbsp;Anything you currently do could be added to your plan, whether it's a spiritual practice, a hobby, something you're learning or some physical training. As a matter of fact, you're twice as likely to achieve your goals with a training plan.<br />
From the <%= link_to "my Plan", :myp %> page, click add activity and save it. &nbsp;You can now mark it as done, and blog about it.</p>

<p style="font-family:serif; font-size:18px"><br />
<span style="font-family:serif; font-size:16px"><strong>Create a course</strong><br />
&nbsp;&nbsp;&nbsp;&nbsp;If you'd like to create a plan to share with others, create a course, publish it, and invite people to join it. &nbsp;Information on creating a course can be found &nbsp;<%= link_to 'here', :gettingstartedcreate %>.</span></p>

</div>

app/views/info/howitworks.html.erb
<% @title = "How it works" %>

<div class='boxed'>

<h2>Overview</h2>
		<p>meLearning is a social learning platform designed to create a sense of support and community.</p>

		<p>Our community allows you to grow in a number of ways from expanding your intellect by learning something new, to improving your mental, emotional or physical health.</p>

		<p>Whether you&rsquo;re a course creator or a participant, meLearning is a community focused on Growth and Support.</p>

		<p><strong>Growth </strong><br />
		meLearning is designed to help you grow mentally, emotionally, physically, and/or spiritually. In order to get the most out of our community, we encourage you to set participate in activities that relate to your interests.</p>

		<p>Participating in community-centered activities is a powerful way to encourage and challenge yourself. Participation in activities can also:</p>

		<ul>
			<li>
			<p>Create a sense of purpose</p>
			</li>
			<li>
			<p>Create a sense of control over your own future</p>
			</li>
			<li>
			<p>Increase your motivation</p>
			</li>
			<li>
			<p>Help you achieve results faster</p>
			</li>
			<li>
			<p>Help you better manage your time</p>
			</li>
			<li>
			<p>Make your thoughts more positive</p>
			</li>
		</ul>

		<p><strong>Support</strong><br />
		Take a look at others&rsquo; Courses and activities. Not only will you find encouragement, but you will also start to generate great ideas that can help you grow and achieve your own goals.</p>

		<p>In addition, you can support and encourage others as they work toward their goals.</p>


		<p>Our mission at meLearning is to connect you with the ideas and resources you need to grow and be healthier mentally, emotionally, physically, intellectually, and spiritually.</p>
		
		
<h2>How it works</h2>

<p>Every member has a plan that's their own that's comprised of activities.</p>
<p>You might have created the activities (say journaling every day), or they may come from a course (like keys to happier living).</p>
<p>You can modify or delete any activities whether you created them or they're from a course, so that your plan is yours and tailored to your situation.</p>
<p>You can keep track of when you do certain activities (commitment marks) as well as blog about them.  You can see all blog entries from others doing the same activities, as well as see how they might have tailored them.</p>
<p></p>
<p>This might all seem abstract.  Let's take Ashley.  She joined a course to learn how to run and keep at it, as well as the four agreements course.  She also would like to journal every day so she added that to her plan. She also noticed she lashes out at her employees when she's annoyed, so she added the commitment to not do that. Now her plan has:</p>
<p><ul>
<li>Activities from the four agreements (there are 4)</li>
<li>Activities from the running course</li>
<li>The journaling activity</li>
<li>The stop lashing at her employees activity</li>
</ul></p>
<p>When she runs she can blog about it as well as mark it as done and add an entry with her thoughts and feelings about it.  When she notices she's taking things personally she can write about it.  She notices she's still taking things personally and is curious how others deal with that.  She looks at other people's entries for that activity and then writes an entry asking for some guidance.</p>
<p>After a couple months she looks at her log of commitment marks and notices she runs every day for a few days and then not at all for a week.  She writes an entry about that insight that will hopefully help her running practice, and she changes her running frequency to every other day, which seems more realistic.</p>
<p>After a couple years her plan is a bit different.  She still runs and shares her experiences with others who do as well.  She looks back at the various insights she's had about running.  They still help her and hopefully others following similar approaches will benefit as well.
</div>